= My Project
David Thaller

//Need this blank line after ifdef, don't know why...
ifdef::backend-html5[]

// print the toc here (not at the default position)
//toc::[]

=== Terminal History Docker run

    sudo apt update
    sudo systemctl start docker
    sudo snap install docker
    sudo service docker start
    sudo apt-get install docker-engine -y
    cd itp
    cd playground/
    mkdir lecture-notes-david
    cd lecture-notes-david/
    git clone git@github.com:2122-3bhitm-itp/04-lecture-notes-git-ThallerDavid.git
    git add .
    git init
    ls
    cd 04-lecture-notes-git-ThallerDavid/
    cd
    cd itp
    cd playground/
    cd lecture-notes-david/
    cd 04-lecture-notes-git-ThallerDavid/
    git add .
    git commit -m"initial commit"
    git push
    cd 04-lecture-notes-git-ThallerDavid/
    ./run-inside-docker.sh 
    docker run
    docker run --help
    sudo service docker start
    sudo apt-get remove docker docker-engine docker.io containerd runc
    sudo apt update
    sudo apt install apt-transport-https ca-certificates curl software-properties-common
    url -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    sudo apt update
    apt-cache policy docker-ce
    sudo apt install docker-ce
    sudo systemctl status docker
    sudo apt-get install apt-transport-https ca-certificates curl software-properties-common
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add
    sudo apt update
    docker --version
    sudo systemctl start docker
    sudo snap install docker
    sudo service docker start
    sudo apt-get install docker-engine -y
    cd itp
    cd playground/
    mkdir lecture-notes-david
    cd lecture-notes-david/
    git clone git@github.com:2122-3bhitm-itp/04-lecture-notes-git-ThallerDavid.git
    git add .
    git init
    ls
    cd 04-lecture-notes-git-ThallerDavid/
    l
    ls
    cd
    cd itp
    cd playground/
    cd lecture-notes-david/
    cd 04-lecture-notes-git-ThallerDavid/
    git add .
    git commit -m"initial commit"
    git push
    nano .env
    l
    cd ..
    l
    nano .env
    cd 04-lecture-notes-git-ThallerDavid/
    ./run-inside-docker.sh 
    docker run
    ./run-inside-docker.sh 
    docker run --help
    docker run -t -i --rm ubuntu bash
    docker run
    docker run --help
    docker run
    sudo service docker start
    run-inside-docker.sh  
    docker
    docker version
    docker run
    docker rm
    run
    docker version 
    docker run
    docker run hello-world
    sudo service docker start
    sudo apt-get update -y && sudo apt-get install -y linux-image-extra-$(uname -r)
    docker run
    clear
    docker run
    clear
    docker run hello-world
    clear
    sudo docker run
    clear
    sudo docker run hello-world
    cd itp
    cd playground
    04-lecture-note
    cd lecture-notes-david/
    cd 04-lecture-notes-git-ThallerDavid/
    ls
   run-inside-docker.sh  
    docker version
    docker run hello-world
    sudo service docker start
    sudo apt-get update -y && sudo apt-get install -y linux-image-extra-$(uname -r)
    docker run
    clear
    docker run
    sudo apt-get remove docker docker-engine docker.io containerd runc
    sudo apt update
    sudo apt install apt-transport-https ca-certificates curl software-properties-common
    url -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    sudo apt update
    apt-cache policy docker-ce
    sudo apt install docker-ce
    sudo systemctl status docker
    clear
    sudo apt-get install apt-transport-https ca-certificates curl software-properties-common
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add
    sudo apt update
    docker --version
    sudo systemctl start docker
    sudo snap install docker
    sudo service docker start
    sudo apt-get install docker-engine -y
    cd itp
    cd playground/
    mkdir lecture-notes-david
    cd lecture-notes-david/
    git clone git@github.com:2122-3bhitm-itp/04-lecture-notes-git-ThallerDavid.git
    git add .
    git init
    ls
    cd 04-lecture-notes-git-ThallerDavid/
    l
    ls
    cd
    cd itp
    cd playground/
    cd lecture-notes-david/
    cd 04-lecture-notes-git-ThallerDavid/
    git add .
    git commit -m"initial commit"
    git push
    nano .env
    l
    cd ..
    l
    nano .env
    cd 04-lecture-notes-git-ThallerDavid/
    ./run-inside-docker.sh 
    docker run
    ./run-inside-docker.sh 
    docker run --help
    docker run -t -i --rm ubuntu bash
    docker run
    docker run --help
    docker run
    sudo service docker start
    run-inside-docker.sh  
    docker
    docker version
    docker run
    docker rm
    run
    docker version 
    docker run
    sudo apt-get update -y && sudo apt-get install -y linux-image-extra-$(uname -r)
    sudo docker run hello-world
    cd itp
    cd playground
    04-lecture-note
    cd lecture-notes-david/
    cd 04-lecture-notes-git-ThallerDavid/
    ls
    docker run hello-world
